baseURL: https://ZQRuii.github.io/blog
languageCode: en-us
title: ZQRui
theme: "PaperMod"
params:
    defaultTheme: auto
    disableThemeToggle: true
    homeInfoParams:
        Title: Rui
        Content: The world means nothing to me without youparams:
    customCSS: true
    # socialIcons: # optional
    #     - name: "<platform>"
    #         url: "<link>"
    #     - name: "<platform 2>"
    #         url: "<link2>"